name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug layout
        run: |
          ls -la
          ls -la services || true
          ls -la services/api || true

      # === PRE-CHEQUEO DE GO (compila fuera de Docker para ver el error real) ===
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Go preflight build
        run: |
          cd services/api
          go env
          go mod tidy
          go build ./...

      # === Docker Buildx ===
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./services/api
          file: ./services/api/Dockerfile
          push: false
          tags: api:latest
