name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug layout
        run: |
          ls -la
          ls -la services || true
          ls -la services/api || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./services/api
          file: ./services/api/Dockerfile
          push: false
          tags: api:latest
