name: Docs Check
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**' ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List docs
        run: ls -la docs
